/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadGrupo54b.entidades.Vistas.formularios;

import javax.swing.JOptionPane;
import universidadGrupo54b.AccesoADatos.MateriaData;
import universidadGrupo54b.entidades.Materia;



/**
 *
 * @author Otras
 */
public class FormularioMateriaView extends javax.swing.JInternalFrame {

    private MateriaData matData = new MateriaData();
    private Materia materiaActual = null;

    /**
     * Creates new form FormularioMateria
     */
    public FormularioMateriaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFCodigo = new javax.swing.JTextField();
        jBbuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTFnombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTFanio = new javax.swing.JTextField();
        jRBestado = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jBnuevo = new javax.swing.JButton();
        jBeliminar = new javax.swing.JButton();
        jBguardar = new javax.swing.JButton();
        jBSALIR = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setBackground(new java.awt.Color(255, 204, 255));
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Formulario de Materia");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 270, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo: ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 28));
        getContentPane().add(jTFCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 260, -1));

        jBbuscar.setBackground(new java.awt.Color(102, 102, 102));
        jBbuscar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBbuscar.setText("Buscar");
        jBbuscar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        jBbuscar.setBorderPainted(false);
        jBbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jBbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 70, 29));

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));
        getContentPane().add(jTFnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 258, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Año:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 27));
        getContentPane().add(jTFanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 56, 27));
        getContentPane().add(jRBestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estado:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        jBnuevo.setBackground(new java.awt.Color(102, 102, 102));
        jBnuevo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBnuevo.setText("Nuevo");
        jBnuevo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        jBnuevo.setBorderPainted(false);
        jBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoActionPerformed(evt);
            }
        });
        getContentPane().add(jBnuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 70, 33));

        jBeliminar.setBackground(new java.awt.Color(102, 102, 102));
        jBeliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBeliminar.setText("Eliminar");
        jBeliminar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        jBeliminar.setBorderPainted(false);
        jBeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBeliminarActionPerformed(evt);
            }
        });
        getContentPane().add(jBeliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 78, 33));

        jBguardar.setBackground(new java.awt.Color(102, 102, 102));
        jBguardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBguardar.setText("Guardar");
        jBguardar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        jBguardar.setBorderPainted(false);
        jBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarActionPerformed(evt);
            }
        });
        getContentPane().add(jBguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 78, 31));

        jBSALIR.setBackground(new java.awt.Color(102, 102, 102));
        jBSALIR.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jBSALIR.setText("Salir");
        jBSALIR.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 51, 102), new java.awt.Color(0, 51, 102)));
        jBSALIR.setBorderPainted(false);
        jBSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSALIRActionPerformed(evt);
            }
        });
        getContentPane().add(jBSALIR, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 75, 33));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FooterUlpVirtualM7.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/55.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 580, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoActionPerformed
        // TODO add your handling code here:
        limpiarCamposMateria();
        materiaActual = null;

    }//GEN-LAST:event_jBnuevoActionPerformed

    private void jBeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBeliminarActionPerformed
        // TODO add your handling code here:
        if(materiaActual!=null){
        matData.eleminarMateria(materiaActual.getIdMateria());
        materiaActual=null;
        limpiarCamposMateria();
        }else{
        JOptionPane.showMessageDialog(this, "No hay una materia Seleccionada. ");
        }
    }//GEN-LAST:event_jBeliminarActionPerformed

    private void jBbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarActionPerformed
        // TODO add your handling code here:
        try {
            Integer codigo;
            codigo = Integer.parseInt(jTFCodigo.getText());
            materiaActual = matData.buscarMateria(codigo);
            if (materiaActual != null) {
                jTFnombre.setText(materiaActual.getNombre());
                jTFanio.setText(String.valueOf(materiaActual.getAnioMateria()));
                //jTFanio.setText("" + materiaActual.getAnioMateria()); OTRA OPCION
                jRBestado.setSelected(materiaActual.isEstado());

            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero de materia válido. ");

        }
    }//GEN-LAST:event_jBbuscarActionPerformed

    private void jBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarActionPerformed
        // TODO add your handling code here:
        try {
            Integer codigo = Integer.parseInt(jTFCodigo.getText());
            String nombre = jTFnombre.getText();
            Integer anio = Integer.parseInt(jTFanio.getText());
            boolean estado = jRBestado.isSelected();

            if (materiaActual == null) {
                materiaActual = new Materia(codigo, nombre, anio, estado);
                matData.guardarMateria(materiaActual);
            } else {
                materiaActual.setIdMateria(codigo);
                materiaActual.setNombre(nombre);
                materiaActual.setAnioMateria(anio);
                //materiaActual.setEstado(true);
                matData.modificarMateria(materiaActual);

            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero de materia válido. ");
        }
    }//GEN-LAST:event_jBguardarActionPerformed

    private void jBSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSALIRActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBSALIRActionPerformed

    private void limpiarCamposMateria() {
        jTFCodigo.setText("");
        jTFnombre.setText("");
        jTFanio.setText("");
        jRBestado.setSelected(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSALIR;
    private javax.swing.JButton jBbuscar;
    private javax.swing.JButton jBeliminar;
    private javax.swing.JButton jBguardar;
    private javax.swing.JButton jBnuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JRadioButton jRBestado;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTextField jTFanio;
    private javax.swing.JTextField jTFnombre;
    // End of variables declaration//GEN-END:variables
}
