/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadGrupo54b.entidades.Vistas.formularios;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;




/**
 *
 * @author Otras
 */
public class MenuGeneral extends javax.swing.JFrame {

    

    /**
     * Creates new form MenuGeneral
     */
    public MenuGeneral() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(600, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        escritorio = new javax.swing.JDesktopPane();
        jMenuBar3 = new javax.swing.JMenuBar();
        alumno = new javax.swing.JMenu();
        FormularioAlumnoView = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        FormularioMateriaView = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMManejoDeInscripciones = new javax.swing.JMenuItem();
        jMcargaDeNotas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FooterUlpVirtualM7.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m_6.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 590, 460));

        escritorio.setPreferredSize(new java.awt.Dimension(700, 600));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 599));

        alumno.setForeground(new java.awt.Color(255, 255, 255));
        alumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/graduacion.png"))); // NOI18N
        alumno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        FormularioAlumnoView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FormularioAlumnoView.setForeground(new java.awt.Color(0, 51, 102));
        FormularioAlumnoView.setText("Formulario de Alumnos");
        FormularioAlumnoView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioAlumnoViewActionPerformed(evt);
            }
        });
        alumno.add(FormularioAlumnoView);

        jMenuBar3.add(alumno);

        jMenu8.setForeground(new java.awt.Color(0, 51, 102));
        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m_educacion4.png"))); // NOI18N
        jMenu8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        FormularioMateriaView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FormularioMateriaView.setForeground(new java.awt.Color(0, 51, 102));
        FormularioMateriaView.setText("Formulario de Materias");
        FormularioMateriaView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FormularioMateriaViewActionPerformed(evt);
            }
        });
        jMenu8.add(FormularioMateriaView);

        jMenuBar3.add(jMenu8);

        jMenu1.setForeground(new java.awt.Color(0, 51, 102));
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m_universidad3.png"))); // NOI18N
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMManejoDeInscripciones.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMManejoDeInscripciones.setForeground(new java.awt.Color(0, 51, 102));
        jMManejoDeInscripciones.setText("Manejo de Inscripciones");
        jMManejoDeInscripciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMManejoDeInscripcionesActionPerformed(evt);
            }
        });
        jMenu1.add(jMManejoDeInscripciones);

        jMcargaDeNotas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMcargaDeNotas.setForeground(new java.awt.Color(0, 51, 102));
        jMcargaDeNotas.setText("Manipulacion de Datos");
        jMcargaDeNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMcargaDeNotasActionPerformed(evt);
            }
        });
        jMenu1.add(jMcargaDeNotas);

        jMenuBar3.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(0, 51, 102));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m_universidad4.png"))); // NOI18N
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem5.setText("Alumnos por Materia");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar3.add(jMenu2);

        MenuSalir.setForeground(new java.awt.Color(0, 51, 102));
        MenuSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/m_salida4.png"))); // NOI18N
        MenuSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MenuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSalirMouseClicked(evt);
            }
        });
        jMenuBar3.add(MenuSalir);

        setJMenuBar(jMenuBar3);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSalirMouseClicked
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_MenuSalirMouseClicked

    private void FormularioAlumnoViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormularioAlumnoViewActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        FormularioAlumnoView  alumno = new FormularioAlumnoView();
        alumno.setVisible(true);
        alumno.getContentPane().setBackground(new Color(255, 153, 255));
        escritorio.add(alumno);
        escritorio.moveToFront(alumno);
    }//GEN-LAST:event_FormularioAlumnoViewActionPerformed

    private void FormularioMateriaViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FormularioMateriaViewActionPerformed
        // TODO add your handling code here:
        escritorio.removeAll();
        escritorio.repaint();
        FormularioMateriaView fm = new FormularioMateriaView();
        fm.setVisible(true);
        fm.getContentPane().setBackground(new Color(255, 193, 255));
        escritorio.add(fm);
        escritorio.moveToFront(fm);
    }//GEN-LAST:event_FormularioMateriaViewActionPerformed

    private void jMManejoDeInscripcionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMManejoDeInscripcionesActionPerformed
        // TODO add your handling code here:
        
        escritorio.removeAll();
        escritorio.repaint();
        FormularioDeInscripcionesView fm = new FormularioDeInscripcionesView();
        fm.setVisible(true);
        fm.getContentPane().setBackground(new Color(255, 193, 255));
        escritorio.add(fm);
        escritorio.moveToFront(fm);
        
        
    }//GEN-LAST:event_jMManejoDeInscripcionesActionPerformed

    private void jMcargaDeNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMcargaDeNotasActionPerformed
       escritorio.removeAll();
        escritorio.repaint();
        CargaDeNotas cdn = new CargaDeNotas();
        cdn.setVisible(true);
        cdn.getContentPane().setBackground(new Color(255, 193, 255));
        escritorio.add(cdn);
        escritorio.moveToFront(cdn);       



    }//GEN-LAST:event_jMcargaDeNotasActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here
       escritorio.removeAll();
        escritorio.repaint();
        ConsultaDeAlumnosPorMateria caxm= new ConsultaDeAlumnosPorMateria();
        caxm.setVisible(true);
        caxm.getContentPane().setBackground(new Color(255, 193, 255));
        escritorio.add(caxm);
        escritorio.moveToFront(caxm);       
 
        
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGeneral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem FormularioAlumnoView;
    private javax.swing.JMenuItem FormularioMateriaView;
    private javax.swing.JMenu MenuSalir;
    private javax.swing.JMenu alumno;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMManejoDeInscripciones;
    private javax.swing.JMenuItem jMcargaDeNotas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
